diff send-page1-ReadSensorHistory.markdown send-page2-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page3-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page4-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page5-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page6-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page7-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page8-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page9-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page10-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page11-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page12-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page13-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page14-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page15-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page16-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page17-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page18-ReadSensorHistory.markdown 
diff send-page1-ReadSensorHistory.markdown send-page19-ReadSensorHistory.markdown 
